Exercise-7: Set up github actions CI with docker container
Peter4137/DevOps-Course-Starter pull request #9
Opened 2022-06-13 08:36 UTC by Peter4137

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-06-13 11:43 UTC, Peter4137 commented
I already had _some_ github actions in place, but not using the docker container, so the changes might look a little odd...

2022-06-13 11:44 UTC, Peter4137 commented on .github/workflows/python-app.yml
> +        echo "${{ secrets.SECRET_ENV }}" > .env
I'm not sure what the best way to do this is with multiple secrets - my current strategy is to make a new .env file (as seen above) from the github secret, and then copy this into the docker container when I do the test build. Is this problematic from a security point of view?

2022-06-21 10:00 UTC, JackMead requested changes
Nice work, I can see your pipeline happily running your tests, but before you merge I think we should adjust your approach to passing through the environment variables; reconstructing your `.env` file is OK, but we do want to avoid copying that into the image at build time. See below for more info

2022-06-21 10:00 UTC, JackMeadDev commented on .github/workflows/python-app.yml
> +        echo "${{ secrets.SECRET_ENV }}" > .env
It shouldn't be problematic _assuming_ we trust GitHub to recycle the runners between runs correctly (so our files are never shown to others) but I'm not convinced that's any riskier than GitHub failing to clean out environment variables

Generally I find it easier though to just pass the variables directly to the docker container (e.g. `docker run -e SECRET_KEY todo_app:test` will pick up the variable if you're using consistent naming inside & outside the container)

Having said the above, baking the `.env` file into your image is _not_ recommended because future users may well choose to share the test image (e.g. pushing layers so you can take advantage of the cache) and you're then securing the secrets alongside the image, so switching to pass it through explicitly at run time is the way we should go here. Assuming you want to keep all your secrets in one, then you can always do it with `docker run --env-file .env todo-app:test`

2022-06-21 10:00 UTC, JackMeadDev commented on test/e2e_tests/e2e_test.py
> +    time.sleep(1)
Sad, but often necessary!

2022-06-21 10:00 UTC, JackMeadDev commented on Dockerfile
> +COPY .env.test .env ./
This is the line that concerns me from above; instead of this try passing the `.env` file (or just the individual variables) through at run time

2022-06-21 10:00 UTC, JackMeadDev commented on .github/workflows/python-app.yml
> +      run: docker run todo_app:test
Side note - it might be nice to run your end-to-end & other tests separately, since otherwise you'll be relying on some non-obvious test behaviour, currently:
* the `.env` file will get passed through and be the default environment
* the e2e tests run first because they're alphabetically first
* the integration tests replace the environment with `.env.test`
* the other tests run

2022-06-21 17:15 UTC, merged

2022-06-22 11:29 UTC, JackMead commented
Thanks for making those changes, happy this is now merged!